export const levels = [
  {
    number: "01",
    title: "Talk to Your Minion",
    concept: "Prompt Engineering",
    description: "Your Minion just arrived. They understand nothing. Learn to give precise, structured orders that actually work.",
    duration: "20 min",
    color: "yellow",
  },
  {
    number: "02",
    title: "Arm Your Minion",
    concept: "Custom GPTs",
    description: "The sun does not steal itself.\nArm your Minion as a data analyst, load 374 mission records, and let them find the pattern nobody spotted.",
    duration: "25 min",
    color: "purple",
  },
  {
    number: "03",
    title: "The Mission Plan",
    concept: "Custom GPTs",
    description: "Gru does not show up unprepared.\nNeither do you.\nUpload your debrief. Get your masterplan.\nThe heist starts here.",
    duration: "15 min",
    color: "blue",
  },
  {
    number: "04",
    title: "Beyond the Mission",
    concept: "AI Opportunity Finder",
    description: "Map where AI can make the biggest difference in your own work. Five questions. One personalised prompt. Your AI plan for FY27.",
    duration: "15 min",
    color: "orange",
  },
  {
    number: "05",
    title: "Mission Debrief",
    concept: "Padlet",
    description: "The heist is complete. Report back to Gru. Share your A-Ha moments, plot twists, questions, and AI ideas with the team.",
    duration: "10 min",
    color: "yellow",
  },
] as const
